name: flutter_jokes
description: A Flutter application to be the life of the party.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ^3.27.1

dependencies:
  flutter:
    sdk: flutter
  jokes:
    path: packages/jokes
  cupertino_icons: ^1.0.2
  dio: ^5.8.0+1
  flutter_riverpod: ^3.0.0-dev.3
  freezed_annotation: ^2.4.4
  http: ^1.3.0
  i18n_extension: ^15.0.4
  mocktail: ^1.0.4
  package_info: ^2.0.0
  riverpod_annotation: ^3.0.0-dev.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.14
  freezed: ^3.0.0-0.0.dev
  riverpod_lint: ^3.0.0-dev.4
  custom_lint: ^0.5.11

flutter:
  uses-material-design: true
