name: flutter_jokes
description: A Flutter application to be the life of the party.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # * Scoped Packages
  network_manager:
    git:
      url: git://github.com/NoScopeDevs/network_manager

  jokes:
    path: packages/jokes

  cupertino_icons: ^1.0.0
  dio: ^3.0.10
  freezed_annotation: ^0.12.0
  http: ^0.12.2
  i18n_extension: ^2.0.0
  package_info: ^0.4.3+4
  meta:
  mockito: ^4.1.4

  #Migration to flutter_bloc
  get_it: ^5.0.6
  flutter_bloc: ^6.1.2
  equatable: ^1.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.11.1
  freezed: ^0.12.7

flutter:
  uses-material-design: true
