name: flutter_jokes
description: A Flutter application to be the life of the party.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ^3.27.1

dependencies:
  flutter:
    sdk: flutter
  jokes:
    path: packages/jokes
  cupertino_icons: ^1.0.2
  dio: ^5.8.0+1
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^2.4.4
  http: ^1.3.0
  i18n_extension: ^15.0.4
  mocktail: ^1.0.4
  package_info: ^2.0.0
  riverpod_annotation: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.14
  freezed: ^2.5.8

flutter:
  uses-material-design: true
