name: jokes
description: Dart package to manage jokes data and domain layers.
version: 0.0.1+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  dio: ^5.8.0+1
  equatable: ^2.0.0
  http: ^1.3.0
  json_annotation: ^4.9.0
  meta: ^1.3.0
  path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.14
  json_serializable: ^6.9.3

  # testing
  mockito: ^5.0.3
  test: ^1.16.8

  # static analysis
  very_good_analysis: ^7.0.0
